config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  # Begin API route
  namespace :api do
    # v1
    namespace :v1 do
      resources :bots, defaults: {format: :json}
      resources :questions
        resources :responses
    end
  end
  # End API route
  match '/' => redirect('/questions'), via: :get
  # Below: Public FE routes
  resources :questions do
    resources :responses
  end
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :responses, dependent: :destroy
  belongs_to :user
  # open : boolean
  # date_asked : date
  scope :open, -> { where(open: true) }

  def mark_as_open!
    update(open: true)
  end

  def mark_as_closed!
    update(open: false, date_asked: Date.today)
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::ApiController
  # Questions Controller
  ################
  
  def index
    render(
      json: Question.all
    )
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.create(question_params)
    redirect_to questions_path()
  end


  def destroy
    Question.destroy(params[:id])
    redirect_to questions_path()
  end

  private 
  
  def question_params
    params[:question].permit(:question).merge(user: User.first)
   end
end

app/views/questions/index.html.erb
<div class="page">
  <h1>All Questions</h1>

  <table>
    <thead>
      <tr>
        <th></th>
        <th>Question</th>
        <th class="text-center">Responses</th>
        <th class="text-center">Open?</th>
        <th>Date Asked</th>
      </tr>
    </thead>
    <tbody>
      <% @questions.each do |q| %>
        <tr>
          <td class="text-center"><span class="status <%= 'answered' if q.responses.length > 0 %>"></span></td>
          <td><%= link_to q.question, question_responses_path(q) %></td>
          <td class="text-center"><%= q.responses.length %></td>
          <td class="text-center"><span class="status <%= 'answered' if q.open %>"></span></td>
          <td>
            <% if q.date_asked %>
              <%= q.date_asked %>
            <% else %>
              <em>pending</em>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div class="actions">
    <%= link_to "Add a Question", { action: "new" }, class: "btn" %>
  </div>
</div>

app/views/questions/new.html.erb
<div class="page">
  <h1>Add Question</h1>

  <%= form_for @question do |f| %>
    <%= f.label(:question, "What do you want to ask your teammates?") %>
    <%= f.text_field :question, :required => 'required' %>
    <%= link_to "Cancel", questions_path, class: "btn btn-gray" %>
    <%= f.submit "Add Question" %>
  <% end %>
</div>