config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  # Begin API route
  namespace :api do
    # v1
    namespace :v1 do
      resources :bots, defaults: {format: :json}
      resources :questions
        resources :responses
    end
  end
  # End API route
  match '/' => redirect('/questions'), via: :get
  # Below: Public FE routes
  resources :questions do
    resources :responses
  end
end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController
  before_action :get_question

  def index
    @responses = @question.responses
  end

  def edit
    @response = @question.responses.find(params[:id])
  end

  def update
    @response = Response.find(params[:id])
    @response.update(response_params)
    if @response.save
      redirect_to question_responses_path(@question)
    end
  end

  def new
    @response = Response.new()
  end

  def create
    @response = @question.responses.new(response_params)
    if @response.save
      redirect_to question_responses_path(@question)
    end
  end

  def destroy
    Response.destroy(params[:id])
    redirect_to question_responses_path(@question)
  end

  private 

  def get_question
    @question = Question.find(params[:question_id])
  end
  
  def response_params
    params[:response].permit(:answer, :user)
   end
end

app/views/responses/_reply.html.erb
<div class="page">
  <h1>Response</h1>

  <%= form_for [question, response] do |f| %>
    <%= f.label(:answer, question.question) %>
    <%= f.text_field :answer, :required => 'required' %>
    <%= link_to "Back", question_responses_path(question), class: "btn btn-gray" %>
    <%= f.submit submit_text %>
  <% end %>
</div>

app/views/responses/edit.html.erb
<%= render partial: "reply", locals: {:question => @question, :response => @response, :submit_text => "Save Changes"} %>

app/views/responses/index.html.erb
<div class="page">
  <h1><%= @question.question %></h1>

  <table>
    <thead>
      <tr>
        <th>User</th>
        <th>Answer</th>
        <%# <th></th> %>
        <th></th>
      </tr>
    </thead>
    <% if @responses.any? %>
      <% @responses.each do |r| %>
        <tr>
          <td><%= r.user.ucode %></td>
          <td><%= r.answer %></td>
          <%# <td class="text-center"> %>
            <%# <%= link_to "✒ Edit", edit_question_response_path(@question, r), action: "edit", class: "primary" %>
          <%# </td> %>
          <td class="text-center">
            <%= link_to "✖ Delete", question_response_path(@question, r), method: :delete, data: {confirm: "Are you sure you want to delete this response?"}, class: "danger" %>
          </td>
        </tr>
      <% end %>
    <% else %>
      <tr><td colspan="3">No responses yet.</td></tr>
    <% end %>
  </table>

  <div class="actions">
    <%= link_to "Back to All Questions", questions_path, class: "btn btn-gray" %>
    <%# <% if @question.open %>
      <%# <%= link_to "Add Response", { action: "new" }, class: "btn" %>
    <%# <% end %>
    <%= link_to 'Delete Question', question_path(@question), method: :delete, data: {confirm: "Are you sure you want to delete this question and all responses?"}, class: "btn btn-danger" %>
  </div>
</div>

app/views/responses/new.html.erb
<%= render partial: "reply", locals: {:question => @question, :response => @response, :submit_text => "Add Response"} %>